from typing import Any

class URLParameters:
    def __init__(self, url: str) -> None: ...

class BlockingConnection:
    def __init__(self, params: URLParameters) -> None: ...
    def channel(self) -> Any: ...
    def close(self) -> None: ...

exceptions: Any
