from collections.abc import Callable
from typing import Any

class Flask:
    def __init__(self, import_name: str, *args: Any, **kwargs: Any) -> None: ...
    def route(self, rule: str, **options: Any) -> Callable[..., Any]: ...
    def before_request(self, func: Callable[..., Any]) -> Callable[..., Any]: ...
    def run(self, *args: Any, **kwargs: Any) -> None: ...


def jsonify(*args: Any, **kwargs: Any) -> Any: ...


request: Any
