from typing import Any

ndarray = Any

lib: Any

def array(*args: Any, **kwargs: Any) -> Any: ...
def empty(*args: Any, **kwargs: Any) -> Any: ...
def frombuffer(*args: Any, **kwargs: Any) -> Any: ...
def concatenate(*args: Any, **kwargs: Any) -> Any: ...
def count_nonzero(*args: Any, **kwargs: Any) -> int: ...
def ptp(*args: Any, **kwargs: Any) -> Any: ...
def reshape(*args: Any, **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
