version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      python-libraries:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker-images:
        patterns:
          - '*'
