services:
  # Disable volume preallocation in CI to prevent disk space exhaustion
  # SeaweedFS's default 1GB preallocation per volume causes "No more free space left"
  # errors in GitHub Actions runners (14GB total disk space)
  object-storage:
    command: >
      server
      -dir=/data
      -s3
      -s3.port=${OBJECT_STORAGE_PORT}
      -s3.port.grpc=18333
      -filer
      -filer.port=8888
      -filer.port.grpc=18888
      -ip=object-storage
      -ip.bind=0.0.0.0
      -volume.port=8080
      -volume.port.grpc=18080
      -volume.max=0
      -master.volumePreallocate=false
      -master.port=9333
      -master.port.grpc=19333

  integration-test:
    build:
      context: .
      dockerfile: integration_test/Dockerfile
    profiles:
      - integration-tests
    environment:
      BASE_URL: ${INTEGRATION_TEST_BASE_URL:-http://ingress/api/v1}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OBJECT_STORAGE_ENDPOINT: ${INTEGRATION_TEST_OBJECT_STORAGE_ENDPOINT:-object-storage}
      OBJECT_STORAGE_PORT: ${OBJECT_STORAGE_PORT}
      OBJECT_STORAGE_USE_SSL: ${OBJECT_STORAGE_USE_SSL}
      OBJECT_STORAGE_ACCESS_KEY: ${OBJECT_STORAGE_ACCESS_KEY}
      OBJECT_STORAGE_SECRET_KEY: ${OBJECT_STORAGE_SECRET_KEY}
      OBJECT_STORAGE_RAW_DATA_BUCKET: ${OBJECT_STORAGE_RAW_DATA_BUCKET}
      OBJECT_STORAGE_MEDIA_BUCKET: ${OBJECT_STORAGE_MEDIA_BUCKET}
      OBJECT_STORAGE_BIDS_EXPORTS_BUCKET: ${OBJECT_STORAGE_BIDS_EXPORTS_BUCKET}
    depends_on:
      ingress:
        condition: service_healthy
      db:
        condition: service_healthy
      object-storage-bootstrap:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      auth_manager:
        condition: service_healthy
      collector:
        condition: service_healthy
      processor:
        condition: service_healthy
      media_processor:
        condition: service_healthy
      realtime_analyzer:
        condition: service_healthy
      session_manager:
        condition: service_healthy
      stimulus_asset_processor:
        condition: service_healthy
      observability_dashboard:
        condition: service_healthy
      data_linker:
        condition: service_healthy
      event_corrector:
        condition: service_healthy
      bids_exporter:
        condition: service_healthy
      erp_neuro_marketing:
        condition: service_healthy
    networks:
      - eeg-network
