from typing import Any, Iterable


class Info:
    def copy(self) -> 'Info': ...
    def set_montage(self, *args: Any, **kwargs: Any) -> None: ...


class Epochs:
    events: Any
    metadata: Any
    info: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_data(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> 'Epochs': ...
    def drop_bad(self, *args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...


def create_info(*args: Any, **kwargs: Any) -> Info: ...
def pick_types(*args: Any, **kwargs: Any) -> Any: ...
def pick_info(*args: Any, **kwargs: Any) -> Any: ...
def make_fixed_length_epochs(*args: Any, **kwargs: Any) -> Any: ...
def events_from_annotations(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...


class RawArray:
    info: Info
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def plot_psd(self, *args: Any, **kwargs: Any) -> Any: ...


class _IO:
    RawArray = RawArray


io: _IO

def __getattr__(name: str) -> Any: ...
