from typing import Any, Mapping

class Response:
    status_code: int
    text: str
    def json(self) -> Any: ...

class AsyncClient:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def post(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    async def get(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    async def __aenter__(self) -> 'AsyncClient': ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...

class Timeout:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class RequestError(Exception): ...
