name: 機能要求
description: 新機能の提案はこちら
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        提案事項を以下の項目にできるだけ詳しく記入してください。

  - type: textarea
    id: background
    attributes:
      label: 背景
      description: なぜこの機能が必要なのか、現在の問題や制限を説明してください
      placeholder: |
        現在の状況や問題点、この機能が解決する課題について説明してください
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: 目的
      description: この機能によって達成したいことを明確に記載してください
      placeholder: |
        この機能の導入により、何を実現したいのかを具体的に記述してください
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案内容
      description: 具体的な機能の内容や実装方法を詳しく説明してください
      placeholder: |
        - 機能の詳細な説明
        - UI/UXの変更がある場合はワイヤーフレームやモックアップ
        - API変更がある場合は仕様
        - 実装方針や技術的な考慮事項
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ基準
      description: この機能が完成したと判断するための基準を記載してください
      placeholder: |
        - [ ] 基準1: ...
        - [ ] 基準2: ...
        - [ ] 基準3: ...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 影響範囲
      description: この機能が既存システムに与える影響を記載してください
      placeholder: |
        - データベーススキーマの変更: あり/なし
        - API の破壊的変更: あり/なし
        - 既存機能への影響: ...
        - パフォーマンスへの影響: ...
        - セキュリティへの影響: ...

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の優先度を選択してください
      options:
        - 低（将来的に実装したい）
        - 中（数ヶ月以内に実装したい）
        - 高（すぐに実装が必要）
        - 緊急（業務に支障がある）
      default: 0

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 検討した代替案があれば記載してください
      placeholder: |
        他に検討した解決方法や実装方法があれば記載してください

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 以下の項目を確認してください
      options:
        - label: 類似の機能要求が既に提出されていないか確認しました
          required: true
        - label: この機能が現在のプロジェクトの目標に沿っていることを確認しました
          required: true
