from typing import Any

class BIDSPath:
    fpath: Any
    directory: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy(self, *args: Any, **kwargs: Any) -> BIDSPath: ...
    def update(self, *args: Any, **kwargs: Any) -> BIDSPath: ...

def read_raw_bids(*args: Any, **kwargs: Any) -> Any: ...
def write_raw_bids(*args: Any, **kwargs: Any) -> Any: ...
