from typing import Any

class Connection:
    def cursor(self, *args: Any, **kwargs: Any) -> Any: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...

def connect(*args: Any, **kwargs: Any) -> Connection: ...
