from typing import Any

class Minio:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def bucket_exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def make_bucket(self, *args: Any, **kwargs: Any) -> None: ...
    def get_object(self, *args: Any, **kwargs: Any) -> Any: ...
    def fget_object(self, *args: Any, **kwargs: Any) -> None: ...
    def fput_object(self, *args: Any, **kwargs: Any) -> None: ...
    def remove_object(self, *args: Any, **kwargs: Any) -> None: ...
